apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-python-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: basic-python-app
  template:
    metadata:
      labels:
        app: basic-python-app
    spec:
      containers:
      - name: flask
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
