apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{  .Values.name }}
  template:
    metadata:
      labels:
        app: {{  .Values.name }}
    spec:
      containers:
        - name: {{  .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}   
          ports:
            - containerPort: {{ .Values.service.port }}

{{- end}}
