apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: birthday-app
  template:
    metadata:
      labels:
        app: birthday-app
    spec:
      containers:
        - name: birthday-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
