wordpress:
  name: wordpress
  image: wordpress:6.4
  replicas: 1

  service:
    type: NodePort
    port: 80
    
  env:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: admin                
    WORDPRESS_DB_PASSWORD: admin        
    WORDPRESS_DB_NAME: wordpress

  pvc:
    enabled: true
    storageClassName: standard   # Change based on your cluster
    accessModes:
      - ReadWriteOnce
    size: 10Gi

mysql:
  name: mysql
  image: mysql:5.7
  rootPassword: rootpass
  database: wordpress
  user: admin                   
  password: admin              
  service:
    port: 3306

  pvc:
    enabled: true
    storageClassName: standard   # Change if needed
    accessModes:
      - ReadWriteOnce
    size: 5Gi
