apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.wordpress.name }}
spec:
  serviceName: {{ .Values.wordpress.name }}
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.env.WORDPRESS_DB_HOST }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.env.WORDPRESS_DB_USER }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.wordpress.env.WORDPRESS_DB_PASSWORD }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.env.WORDPRESS_DB_NAME }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: wordpress-persistent-storage
      spec:
        accessModes: {{ .Values.wordpress.pvc.accessModes }}
        storageClassName: {{ .Values.wordpress.pvc.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.wordpress.pvc.size }}
