replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 32000

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

configMap:
  enabled: true
  name: jenkins-config
  data:
    JENKINS_OPTS: "--prefix=/jenkins"
    "USERNAME": "admin"
    "AUTHOR": "raja kumar gaur"
    "DEPARTMENT": "devops"
