name: birthday

enabled: true
replicaCount: 1

image:
  repository: your-dockerhub-username/birthday-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: birthday-service
  type: ClusterIP
  port: 5001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
