{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  JENKINS_OPTS: "{{ .Values.configMap.JENKINS_OPTS }}"
  USERNAME:  "{{ .Values.configMap.USERNAME}}"
  DEPARTMENT: "{{ .Values.configMap.DEPARTMENT}}"
  AUTHOR: "{{ .Values.configMap.AUTHOR}}"
{{- end }}
