{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  JENKINS_OPTS: "{{ .Values.configMap.data.JENKINS_OPTS }}"
  USERNAME: "{{ .Values.configMap.data.USERNAME }}"
  DEPARTMENT: "{{ .Values.configMap.data.DEPARTMENT }}"
  AUTHOR: "{{ .Values.configMap.data.AUTHOR }}"
{{- end }}
