apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  serviceName: jenkins                  # Headless service required for StatefulSet
  replicas: {{ .Values.replicaCount }}  # Number of Jenkins replicas
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"   # Jenkins image
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080                   # Jenkins web UI port
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home          # Persistent Jenkins home
          {{- if .Values.configMap.enabled }}
          envFrom:                                  # Inject env variables from ConfigMap
            - configMapRef:
                name: {{ .Values.configMap.name }}
          {{- end }}
          resources:                                # CPU & memory resources
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:                             # Auto-create PVC per replica
    - metadata:
        name: jenkins-home
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}   # PVC size from values.yaml
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
